---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-office-search-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 3003
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - https://nav-office-search-api.intern.nav.no
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
    - name: NORG_ENHET_API
      value: https://norg2.intern.nav.no/norg2/api/v1/enhet
    - name: TPS_ADRESSESOK_API
      value: https://tpsws.intern.nav.no/api/v1/adressesoek
  webproxy: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: nav-office-search
          namespace: personbruker
          cluster: prod-gcp
    outbound:
      external:
        - host: norg2.intern.nav.no
        - host: tpsws.intern.nav.no
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
