---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-office-search-api
  namespace: {{namespace}}
  labels:
    team: personbruker
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 3003
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  {{#each env}}
    - name: {{this.name}}
      value: {{this.value}}
  {{/each}}
  webproxy: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: nav-office-search
          namespace: personbruker
          cluster: prod-gcp
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: '2'
      memory: 1024Mi
    requests:
      memory: 512Mi
